---
# This role deploys a GammaBox on a Raspberry Pi Raspbian.

#################################################################################
# Runtimes.
#################################################################################

# TODO Make it work with stock Debian python3-pip.
# Else add instructions
# - name: Install Pip locally
#   pip:
#     name: pip
#     state: present
#     executable: pip3
#     extra_args: --user -U

- name: Install Pipenv
  pip:
    name: pipenv
    state: present
    executable: /$HOME/.local/bin/pip3
    extra_args: --user

#################################################################################
# Code directory (Git checkout).
#################################################################################

- name: Cloning git repository and setting the branch
  git:
    repo: "{{ gammabox_git.url }}"
    dest: "{{ gammabox_path }}"
    version: "{{ gammabox_git.branch }}"
    clone: yes

#################################################################################
# Application dependencies.
#################################################################################

# TODO Create a make install entry.
# - name: Run make install
- name: Install Python dependencies
  # become: yes
  shell: cd {{ gammabox_path }} && /$HOME/.local/bin/pipenv install

#################################################################################
# Gamma Box settings.
#################################################################################

# TODO Create the config file.

# - name: Create app_zend config
#   become: yes
#   template:
#     src: config.json.dev.j2
#     dest: '{{ web.path }}/app_zend/config/local.json'

#################################################################################
# Set up Gamma Box service and launch it.
#################################################################################


#################################################################################
# Public www.
#################################################################################

# TODO Option to deploy under a Nginx/lighttpd server,
# with SSL/TLS Let's Encrypt certificate?


#################################################################################
# Deployment checks.
#################################################################################

# TODO Get host ip. However will only work when deployment in the same network.
# (or on exposed port)
# - name: Test the {{ web.host_front }} website is up
#   uri:
#     url: https://{{ web.host_front }}
#     status_code: 200
#   delegate_to: localhost
#   become: no
