---
# This role deploys a GammaBox on a Raspberry Pi Raspbian.

#################################################################################
# Runtimes.
#################################################################################

- name: Install Pipenv
  pip:
    name: pipenv
    state: present
    executable: "{{ gammabox_pip_bin }}"
    extra_args: --user

- name: Configure PIPENV_TIMEOUT environment variable
  lineinfile:
    path: $HOME/.profile
    line: 'export PIPENV_TIMEOUT=500'
    insertafter: 'EOF'
    state: present

#################################################################################
# Code directory (Git checkout).
#################################################################################

- name: Cloning git repository and setting the branch
  git:
    repo: "{{ gammabox_git.url }}"
    dest: "{{ gammabox_path }}"
    version: "{{ gammabox_git.branch }}"
    clone: yes

#################################################################################
# Application dependencies.
#################################################################################

# TODO Create a make install entry.
# - name: Run make install
- name: Install Python dependencies
  shell: cd {{ gammabox_path }} && /$HOME/.local/bin/pipenv install
  environment:
    - PIPENV_TIMEOUT: 500

#################################################################################
# Gamma Box settings.
#################################################################################

# TODO Create the config file.

# - name: Create app_zend config
#   become: yes
#   template:
#     src: config.json.dev.j2
#     dest: '{{ web.path }}/app_zend/config/local.json'

#################################################################################
# Set up Gamma Box service and launch it.
#################################################################################


#################################################################################
# Public www.
#################################################################################

# TODO Option to deploy under a Nginx/lighttpd server,
# with SSL/TLS Let's Encrypt certificate?


#################################################################################
# Deployment checks.
#################################################################################

# TODO Get host ip. However will only work when deployment in the same network.
# (or on exposed port)
# - name: Test the {{ web.host_front }} website is up
#   uri:
#     url: https://{{ web.host_front }}
#     status_code: 200
#   delegate_to: localhost
#   become: no
